<?php
// $Id$

/**
 * SCORM 2004 Sharable Content Object (SCO)
 *
 * @author
 * Stefan Auditor <stefan.auditor@erdfisch.de>
 */

define("SCORM_SCO_DIRECTORY", 'scorm');

/**
 * Implementation of hook_menu().
 */
function sco_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'view':
// TODO:
//      $node->content['sco'] = array(
//        '#value' => '<div  id="API_1484_11"><iframe id="API_1484_11_iframe" name="scorm" style="height:550px;width:100%;border:0;" src="'. base_path() . drupal_get_path('module', 'scorm_rte') .'/docs/proddingsco/proddingsco.htm"></iframe></div>',
//        '#weight' => -10,
//      );
      break;
    case 'insert':
    case 'update':
      //TODO: Check for node type
      $directory = file_directory_path() .'/'. SCORM_SCO_DIRECTORY;
      if (file_check_directory($directory, TRUE) AND count($node->files)) {
        if ($file = sco_unpack($node)) {
          //dsm($file);
          $imsmanifest = sco_parse_imsmanifest($file->imsmanifest);
          if (is_object($imsmanifest)) {
            dsm($imsmanifest);
            dsm($file);
          }
          db_queryd("INSERT INTO {sco} SET nid = %d, fid = %d, imsmanifest = '%s', default_resource = '%s', completion_threshold = '%s', scaled_passing_score = '%s', time_limit_action = '%s'", $node->nid, $file->fid, $file->imsmanifest, $imsmanifest->default_resource, $imsmanifest->completion_threshold, $imsmanifest->scaled_passing_score, $imsmanifest->time_limit_action);
        }
      }
      break;
  }
}

/**
 * Implementation of hook_form_alter().
 */
function sco_form_alter($form_id, &$form) {
  //TODO: Check for node type
  if (strpos($form_id, '_node_form')) {
    //drupal_set_message('<pre>'. print_r($form, 1) .'</pre>');
    $form['attachments']['#collapsed'] = FALSE;
    $form['attachments']['#weight'] = 0;
    $form['attachments']['#title'] = t('Sharable Content Object');
    $form['attachments']['#description'] = t('<div>A SCO is a collection of one or more Assets that represent a single launchable learning resource. Only the first *.zip file will be consired a SCO.</div>'). $form['attachments']['#description'];
    $form['attachments']['wrapper']['new']['upload']['#title'] = t('Attach new SCO');
  }
}

/**
 * Unpack a packed SCO
 */
function sco_unpack($node) {
  $files = $node->files;
  $imsmanifest = FALSE;

  foreach ($files as $fid => $file) {
    $file = (array) $file;

    //drupal_set_message(print_r($file, 1));
    switch ($file['filemime']) {
      case 'application/zip':
        $zip = new ZipArchive;
        $directory = file_directory_path() .'/'. SCORM_SCO_DIRECTORY .'/'. $file['fid'];
        if ($zip->open($file['filepath']) === TRUE) {
          $zip->extractTo($directory);
          $zip->close();

          // Search for imsmanifest.xml
          $mask = '^(imsmanifest.xml)$';
          $imsmanifest = file_scan_directory($directory, $mask);
          return (object) array('fid' => $file->fid, 'imsmanifest' => $imsmanifest);
        }
        break;
    }
  }

  return FALSE;
}

/**
 *
 */
function sco_parse_imsmanifest($file) {
  if (count($file)) {
    $filepath = key($file);

    $handle = fopen($filepath, "r");
    $contents = fread($handle, filesize($filepath));
    fclose($handle);

    $xml = new SimpleXMLElement($contents);
    $xml->registerXPathNamespace('imscp', 'http://www.imsglobal.org/xsd/imscp_v1p1');
    //drupal_set_message('<pre>data:'. print_r(($xml), 1) .'</pre>');

    $xpath = "//imscp:organizations/@default";
    $default = $xml->xpath($xpath);
    $default = (array) $default[0];
    $default = $default['@attributes']['default'];

    $xpath = "//imscp:organization[@identifier='". $default ."']";
    $identifierref = $xml->xpath($xpath);
    $identifierref = (array) $identifierref[0]->item;
    $identifierref = $identifierref['@attributes']['identifierref'];

    $xpath = "//imscp:resource[@identifier='". $identifierref ."']/@href";
    $resource = $xml->xpath($xpath);
    $resource = (array) $resource[0];
    $values->default_resource = $resource['@attributes']['href'];

    $xpath = "//adlcp:completionThreshold";
    $completion_threshold = $xml->xpath($xpath);
    $completion_threshold = (array) $completion_threshold[0];
    $values->completion_threshold = $completion_threshold[0];

    $xpath = "//imscp:item/imsss:sequencing/imsss:objectives/imsss:primaryObjective/@satisfiedByMeasure";
    $satisfiedByMeasure = $xml->xpath($xpath);
    $satisfiedByMeasure = (array) $satisfiedByMeasure[0];
    $satisfiedByMeasure = $satisfiedByMeasure['@attributes']['satisfiedByMeasure'];
    if ($satisfiedByMeasure == 'true') {
      $xpath = "//imscp:item/imsss:sequencing/imsss:objectives/imsss:primaryObjective/imsss:minNormalizedMeasure";
      $minNormalizedMeasure = $xml->xpath($xpath);
      $minNormalizedMeasure = (array) $minNormalizedMeasure[0];
      $minNormalizedMeasure = $minNormalizedMeasure[0];
      $values->scaled_passing_score = $minNormalizedMeasure;
      if (empty($values->scaled_passing_score)) {
        $values->scaled_passing_score = 1.0; // default
      }
    }
    else {
      $values->scaled_passing_score = NULL;
    }

    $xpath = "//imscp:item/adlcp:timeLimitAction";
    $time_limit_action = $xml->xpath($xpath);
    $time_limit_action = (array) $time_limit_action[0];
    $values->time_limit_action = $time_limit_action[0];
    if (empty($values->time_limit_action)) {
      $values->time_limit_action = 'continue,no message'; // default
    }
  }

  return $values;
}
